# Generated by Django 5.2.7 on 2025-11-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeSteps',
            new_name='RecipeStep',
        ),
    ]
