# Generated by Django 5.2.7 on 2025-11-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_recipesteps_recipestep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientcategory',
            options={'verbose_name_plural': 'Ingredient Categories'},
        ),
        migrations.AlterModelOptions(
            name='recipiecategory',
            options={'verbose_name_plural': 'Recipe Categories'},
        ),
        migrations.AddField(
            model_name='ingredientcategory',
            name='parent_category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
