# Generated by Django 5.2.7 on 2025-11-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_recipeingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='image',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
