# Generated by Django 5.2.7 on 2025-11-16 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ingredientcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ingredientcategory'),
        ),
    ]
