# Generated by Django 5.2.7 on 2025-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_recipestep_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
